# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  database: noise_development
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: noise_festivals_production
  pool: 5
  username: root
  password: <%= ENV["FESTIVALS_DATABASE_PASSWORD"] %>
  socket: /var/run/mysqld/mysqld.sock
  port: 3306
